version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-python-playwright-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    restart: unless-stopped
